version: '3.4'

# mysql 公共配置
x-mysql-environment: &mysql-environment
  XPROFILER_CONSOLE_MYSQL_HOST: "xtransit-mysql"              # xprofiler-console 数据库配置
  XPROFILER_CONSOLE_MYSQL_PORT: 3306
  XPROFILER_CONSOLE_MYSQL_USER: "root"
  XPROFILER_CONSOLE_MYSQL_PASSWORD: "123456"
  XPROFILER_CONSOLE_MYSQL_DATABASE: "xprofiler_console"   # xprofiler_console 数据库名称
  XPROFILER_LOGS_MYSQL_HOST: "xtransit-mysql"                 # xprofiler-logs 数据库配置
  XPROFILER_LOGS_MYSQL_PORT: 3306                         
  XPROFILER_LOGS_MYSQL_USER: "root"                       
  XPROFILER_LOGS_MYSQL_PASSWORD: "123456"                 
  XPROFILER_LOGS_MYSQL_DATABASE: "xprofiler_logs"         # xprofiler_logs 数据库名称

# redis 公共配置
x-redis-environment: &redis-environment
  REDIS_HOST: "xtransit-redis"
  REDIS_PORT: 6379
  REDIS_PASSWORD: ""
  REDIS_DB: 0

# mailer 公共配置
x-mailer-environment: &mailer-environment
  MAILER_HOST: ""
  MAILER_PORT: 25
  MAILER_SECURE: "true"
  MAILER_AUTH_USER: ""
  MAILER_AUTH_PASS: ""

services: 
  xtransit-mysql: 
    container_name: xtransit-mysql
    image: mysql:5.7.22
    restart: always
    # ports: 
    #   - "3306:3306"
    volumes:  # 执行sql初始化数据库，数据库没初始化成功时会导致下面几个依赖该数据库的服务启动失败，耐心等待一会即可，容器会自动重启
      - "./db/xprofiler_console/init.sql:/docker-entrypoint-initdb.d/1_init.sql"
      - "./db/xprofiler_logs/init.sql:/docker-entrypoint-initdb.d/2_init.sql"
      - "./db/xprofiler_logs/date.sql:/docker-entrypoint-initdb.d/3_date.sql"
      - "./mysql:/var/lib/mysql"   # 挂载数据目录
    environment: 
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ROOT_HOST: "%"
  
  xtransit-redis:
    container_name: xtransit-redis
    restart: always
    image: redis
    # ports:
    #   - 6379:6379

  xprofiler-console:
    container_name: xprofiler-console
    image: dq198/xprofiler-console:v1.0.1
    hostname: xprofiler-console
    restart: always
    # cpus: 1  # 1核 cpu
    # mem_limit: 200m  # 200MB 内存
    # command: "./node_modules/.bin/egg-scripts start --workers=4 --port=8443"
    ports: 
      - 8443:8443
    depends_on:
      - xtransit-mysql
      - xtransit-redis
    environment: 
      <<: *mysql-environment
      <<: *redis-environment
      XPROFILER_CONSOLE_URL: "http://127.0.0.1:8443"   # xprofiler-console 服务地址，这里最好配置服务器地址，要不然在界面操作 文件-》转储 时会失败
      XTRANSIT_MANAGER_URL: http://xtransit-manager:8543       # xtransit-manager 服务地址，也可以填服务器ip

  xtransit-manager:
    container_name: xtransit-manager
    image: dq198/xtransit-manager:v1.0.1
    hostname: xtransit-manager
    restart: always
    # cpus: 1
    # mem_limit: 200m
    ports: 
      - 8543:8543
    depends_on:
      - xtransit-mysql
      - xtransit-redis
    environment: 
      <<: *mysql-environment
      <<: *redis-environment
      <<: *mailer-environment
      XPROFILER_CONSOLE_URL: "http://xprofiler-console:8443"   # xtransit-manager 服务地址

  xtransit-server:
    container_name: xtransit-server
    image: dq198/xtransit-server:v1.0.1
    restart: always
    hostname: xtransit-server
    # cpus: 1
    # mem_limit: 200m
    ports: 
      - 9090:9090
    depends_on:
      - xtransit-mysql
      - xtransit-redis
    environment: 
      XTRANSIT_MANAGER_URL: http://xtransit-manager:8543      # xtransit-manager 服务地址